spring:
  profiles:
    active: dev
  resources:
    # 默认资源映射
    add-mappings: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  data:
    rest:
      base-path: /api
logging:
  level:
#    org:
#      hibernate: DEBUG
    com:
      zaxxer:
        hikari:
         HikariConfig: DEBUG
# 自定义配置
project:
  jwt-secret: DFGH(*&FD(G)^&URG)YU&*F)DSG*H(*